# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4e66',
                'verbose_name_plural': '\u4e66',
            },
        ),
    ]
